### PR TITLE
Add a missing LICENSE file

### PR DESCRIPTION
**Pull request by sergey-alekseev**
Copied from https://opensource.org/licenses/MIT.

[ci skip]

### CODE REVIEW

**Comment by sergey-alekseev** [comment]
To clarify why I'm adding this: the LICENSE file is necessary to satisfy https://github.com/github/licensed.

**Comment by grosser** [comment]
are you using these gems ?

**Comment by sergey-alekseev** [comment]
@grosser yes, I have them as dependencies of other gems.

**Comment by grosser** [comment]
usually the gemspecs license field should be good enough ... but feel free to add the actual text 🤷‍♂

**Comment by sergey-alekseev** [comment]
Not for Licensed – https://github.com/github/licensed/blob/f5d0d9b0448ce45394587210286ad8a69534d8cc/lib/licensed/commands/status.rb#L32.

**Pull request merged**
